// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package sensors is a generated GoMock package.
package sensors

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// PublishSensorBatch mocks base method.
func (m *MockPublisher) PublishSensorBatch(value []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSensorBatch", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSensorBatch indicates an expected call of PublishSensorBatch.
func (mr *MockPublisherMockRecorder) PublishSensorBatch(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSensorBatch", reflect.TypeOf((*MockPublisher)(nil).PublishSensorBatch), value)
}
